name: orchid
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - black
  - numpy=1.21.5
  - openjdk
  - perl
  - python=3.9
  - pytorch
  - pip>=22.1
  - scikit-learn
  - matplotlib
  - pip:
      - jsonlines
      - mypy>=0.982
      - pre-commit>=2.20
      - pytest
      - toml
      - transformers==4.18.0
      - types-toml
      - tabulate
